{
 "title": "Week9-App",
 "description": "自定义业务指标的弹性伸缩",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "实时 QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"week9-prometheus-app-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"week9-prometheus-app-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(response_status{job=\"week9-prometheus-app-service\"}) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求延迟百分数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{job=\"week9-prometheus-app-service\"}[1m])) by(le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_response_time_seconds_bucket{job=\"week9-prometheus-app-service\"}[1m])) by(le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket{job=\"week9-prometheus-app-service\"}[1m])) by(le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{job=\"week9-prometheus-app-service\"}[1m])) by(le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接口 QPS 明细",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"week9-prometheus-app-service\"}[1m])) by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求延迟热力图",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_bucket{job=\"week9-prometheus-app-service\"}[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}