apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.mygroup.example.com
spec:
  group: mygroup.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # 修正：业务字段直接放在第一层spec下，删除冗余的内层spec
            spec:
              type: object
              properties:
                field1:
                  type: string
                  description: "This is the first field"
                field2:
                  type: string
                  description: "This is the second field"
              # 可选：声明spec为必填字段，强制用户创建CR时填写field1/field2
              # required: [field1, field2]
            # 核心修复：status字段添加x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: myresources
    singular: myresource
    kind: MyResource
    shortNames:
      - myres